package ar.com.pa.utils;

public enum ViewEnum {
	VIEW_ONBOARDING_GLOBAL_CASES, 
	VIEW_VALIDATION_IDENTITY_LEADS,
	VIEW_LEADS,
	VIEW_LEADS_MAGIC_LINK,
	VIEW_LEADS_EMAIL_VALIDATED,
	VIEW_LEADS_IDENTITY_VERIFIED,
	VIEW_LEADS_AFFIDAVIT,
	VIEW_LEADS_TYC_ACCEPTED,
	VIEW_LEADS_PASSCODE_CREATED
}
